### ISSUE TITLE
Error: image sebfia/ib_gateway_installer not found

### ISSUE THREAD

**Issue by kennethschoultz** [sebfia/ib-gateway-docker#1]
When trying this:
[ec2-user@ip-xxx-xx-xx-xxx ~]$ sudo docker run -e VNC_PASSWORD=xxxxxx -p 5900:5900 sebfia/ib_gateway_installer

I get this:
Unable to find image 'sebfia/ib_gateway_installer:latest' locally
Pulling repository docker.io/sebfia/ib_gateway_installer
docker: Error: image sebfia/ib_gateway_installer not found.

Any ideas what am I missing?

**Comment by sebfia** [comment]
The readme points to a wrong image on docker-hub that has been renamed recently. The correct name for the image to pull is sebfia/ib-gateway-stable. Sorry for missing this out! I have corrected the readme now.
