### ISSUE TITLE
Any plans to package 956.2l ?

### ISSUE THREAD

**Issue by kennethschoultz** [sebfia/ib-gateway-docker#2]
Do you have any plans to package version 956.2l of IB Gateway, i.e. the latest version, now with a different distribution logic as I have understood? IB says it would be needed to avoid a problem with receiving market data after the "the gateway has been reset".

**Comment by sebfia** [comment]
The new distribution logic is a challenge, given the short time I have to take care of this.
As soon as I have some spare time I will bring the image up to the latest version - promised!

**Comment by sebfia** [comment]
Closed with latest commit.
